import { SimulationPreset } from "./types";

/**
 * One preset per test sheet in `ai-agent/image_test/ing003/`, carrying the same data as the image
 * (generated from its `casos.json`), so each case can be driven through the screen without calling
 * the AI.
 *
 * They run against EntryOrderTestSeeder, which issues R1 for the orders in transit, one blank
 * line per head (EN-20260928-0004 with 10 head to receive, EN-20260928-0005 with 10 of both sexes,
 * EN-20260928-0006 with 8, weighed with one average); the lines written here are the caravans of
 * the animals that arrived. 01, 02, 03, 05, 09, 10 and 11 load one after the other on one fresh
 * seed (EN-20260928-0012 is written in words, 0013 has injured animals). The
 * "Varias categorías" cases (no test image yet) run against EN-20260928-0011, whose males declare
 * their category number (Cat.):
 *     php artisan tenants:seed --class=EntryOrderTestSeeder
 */

const REQUIRES = " Requiere EntryOrderTestSeeder.";

const sheetCase = (label: string, description: string, context: Record<string, unknown>, rows: Record<string, string>[]): SimulationPreset => ({
  templateCode: "ING-03",
  scenario: "SHEET_CASES",
  scenarioLabel: label,
  scenarioDescription: description + REQUIRES,
  templateTitle: "Recepción de DTE",
  category: "ENTRY",
  context,
  rows,
});

export const ING03_SHEET_CASES: SimulationPreset[] = [
  sheetCase(
    "🟡 01 · Parcial: dos llegan después",
    "EN-20260928-0004 R1 (10 cabezas a recibir): se escribieron ING-T-14..21 con peso y EC; dos renglones quedaron en blanco. La revisión pregunta por las 2 que faltan: por defecto llegan después y quedan en tránsito.",
    {"orden_ingreso": "EN-20260928-0004", "hoja_recepcion": "R1", "dte": "DTE-TEST-ING-002", "fecha_recepcion": "03/10/2026", "observaciones": "", "hoja_numero": 1, "hoja_total": 1},
    [{"id": "1", "caravana": "ING-T-14", "sexo": "", "raza": "", "ec": "3", "peso": "180"}, {"id": "2", "caravana": "ING-T-15", "sexo": "", "raza": "", "ec": "3,5", "peso": "176"}, {"id": "3", "caravana": "ING-T-16", "sexo": "", "raza": "", "ec": "2,5", "peso": "190"}, {"id": "4", "caravana": "ING-T-17", "sexo": "", "raza": "", "ec": "3", "peso": "185"}, {"id": "5", "caravana": "ING-T-18", "sexo": "", "raza": "", "ec": "3,5", "peso": "172"}, {"id": "6", "caravana": "ING-T-19", "sexo": "", "raza": "", "ec": "4", "peso": "198"}, {"id": "7", "caravana": "ING-T-20", "sexo": "", "raza": "", "ec": "3", "peso": "183"}, {"id": "8", "caravana": "ING-T-21", "sexo": "", "raza": "", "ec": "3,5", "peso": "179"}]
  ),
  sheetCase(
    "🔴 02 · Inválida para reparar",
    "EN-20260928-0005 R1, tropa de ambos sexos: sin fecha, ING-T-32 sin sexo, EC 6 en ING-T-33 (fuera de la escala 1 a 5) e ING-T-35 escrita dos veces. La revisión bloquea; corregí y registrá. El chip rojo del encabezado abre la guía de errores por tipo.",
    {"orden_ingreso": "EN-20260928-0005", "hoja_recepcion": "R1", "dte": "DTE-TEST-ING-003", "fecha_recepcion": "", "observaciones": "", "hoja_numero": 1, "hoja_total": 1},
    [{"id": "1", "caravana": "ING-T-31", "sexo": "M", "raza": "", "ec": "3", "peso": "160"}, {"id": "2", "caravana": "ING-T-32", "sexo": "", "raza": "", "ec": "3", "peso": "165"}, {"id": "3", "caravana": "ING-T-33", "sexo": "M", "raza": "", "ec": "6", "peso": "168"}, {"id": "4", "caravana": "ING-T-34", "sexo": "M", "raza": "", "ec": "", "peso": "171"}, {"id": "5", "caravana": "ING-T-35", "sexo": "M", "raza": "", "ec": "", "peso": "174"}, {"id": "6", "caravana": "ING-T-36", "sexo": "H", "raza": "", "ec": "", "peso": "177"}, {"id": "7", "caravana": "ING-T-37", "sexo": "H", "raza": "", "ec": "", "peso": "180"}, {"id": "8", "caravana": "ING-T-38", "sexo": "H", "raza": "", "ec": "", "peso": "183"}, {"id": "9", "caravana": "ING-T-39", "sexo": "H", "raza": "", "ec": "", "peso": "186"}, {"id": "10", "caravana": "ING-T-40", "sexo": "H", "raza": "", "ec": "", "peso": "189"}, {"id": "11", "caravana": "ING-T-35", "sexo": "H", "raza": "", "ec": "", "peso": "170"}]
  ),
  sheetCase(
    "🟢 03 · Recepción completa",
    "EN-20260928-0005 R1: llegan las diez (5 machos y 5 hembras) con peso y EC. La orden queda completa, con novedades de machos y hembras de más (se compraron 4 y 4).",
    {"orden_ingreso": "EN-20260928-0005", "hoja_recepcion": "R1", "dte": "DTE-TEST-ING-003", "fecha_recepcion": "03/10/2026", "observaciones": "", "hoja_numero": 1, "hoja_total": 1},
    [{"id": "1", "caravana": "ING-T-31", "sexo": "M", "raza": "", "ec": "3", "peso": "162"}, {"id": "2", "caravana": "ING-T-32", "sexo": "M", "raza": "", "ec": "3,5", "peso": "165"}, {"id": "3", "caravana": "ING-T-33", "sexo": "M", "raza": "", "ec": "3", "peso": "168"}, {"id": "4", "caravana": "ING-T-34", "sexo": "M", "raza": "", "ec": "3,5", "peso": "171"}, {"id": "5", "caravana": "ING-T-35", "sexo": "M", "raza": "", "ec": "3", "peso": "174"}, {"id": "6", "caravana": "ING-T-36", "sexo": "H", "raza": "", "ec": "3,5", "peso": "177"}, {"id": "7", "caravana": "ING-T-37", "sexo": "H", "raza": "", "ec": "3", "peso": "180"}, {"id": "8", "caravana": "ING-T-38", "sexo": "H", "raza": "", "ec": "3,5", "peso": "183"}, {"id": "9", "caravana": "ING-T-39", "sexo": "H", "raza": "", "ec": "3", "peso": "186"}, {"id": "10", "caravana": "ING-T-40", "sexo": "H", "raza": "", "ec": "3,5", "peso": "189"}]
  ),
  sheetCase(
    "🟢 05 · Peso promedio (hoja horizontal)",
    "EN-20260928-0006 R1, pesada con un promedio: PESO PROMEDIO 182 kg en el encabezado, ING-T-41..47 llegan con su EC y un renglón queda en blanco (en tránsito). Cada caravana recibida queda con 182 kg, registrado como promedio.",
    {"orden_ingreso": "EN-20260928-0006", "hoja_recepcion": "R1", "dte": "DTE-TEST-ING-004", "fecha_recepcion": "04/10/2026", "observaciones": "", "peso_promedio": "182", "hoja_numero": 1, "hoja_total": 1},
    [{"id": "1", "caravana": "ING-T-41", "sexo": "", "raza": "", "ec": "3", "peso": ""}, {"id": "2", "caravana": "ING-T-42", "sexo": "", "raza": "", "ec": "3,5", "peso": ""}, {"id": "3", "caravana": "ING-T-43", "sexo": "", "raza": "", "ec": "3", "peso": ""}, {"id": "4", "caravana": "ING-T-44", "sexo": "", "raza": "", "ec": "2,5", "peso": ""}, {"id": "5", "caravana": "ING-T-45", "sexo": "", "raza": "", "ec": "3", "peso": ""}, {"id": "6", "caravana": "ING-T-46", "sexo": "", "raza": "", "ec": "3,5", "peso": ""}, {"id": "7", "caravana": "ING-T-47", "sexo": "", "raza": "", "ec": "4", "peso": ""}]
  ),
  sheetCase(
    "🟢 Varias categorías: Cat. por renglón",
    "EN-20260928-0011 R1 (6 Novillito + 4 Torito + 5 Vaquillona, ambos sexos): cada macho lleva su Cat. (1 Novillito, 2 Torito); las hembras no, porque sólo pueden ser Vaquillona. Llegan las 15 y cada caravana queda con su categoría.",
    {"orden_ingreso": "EN-20260928-0011", "hoja_recepcion": "R1", "dte": "DTE-TEST-ING-009", "fecha_recepcion": "04/10/2026", "observaciones": "", "hoja_numero": 1, "hoja_total": 1},
    [{"id": "1", "caravana": "ING-T-51", "sexo": "M", "cat": "1", "raza": "", "ec": "3", "peso": "211"}, {"id": "2", "caravana": "ING-T-52", "sexo": "M", "cat": "1", "raza": "", "ec": "3", "peso": "212"}, {"id": "3", "caravana": "ING-T-53", "sexo": "M", "cat": "1", "raza": "", "ec": "3", "peso": "213"}, {"id": "4", "caravana": "ING-T-54", "sexo": "M", "cat": "1", "raza": "", "ec": "3", "peso": "214"}, {"id": "5", "caravana": "ING-T-55", "sexo": "M", "cat": "1", "raza": "", "ec": "3", "peso": "215"}, {"id": "6", "caravana": "ING-T-56", "sexo": "M", "cat": "1", "raza": "", "ec": "3", "peso": "216"}, {"id": "7", "caravana": "ING-T-57", "sexo": "M", "cat": "2", "raza": "", "ec": "3", "peso": "217"}, {"id": "8", "caravana": "ING-T-58", "sexo": "M", "cat": "2", "raza": "", "ec": "3", "peso": "218"}, {"id": "9", "caravana": "ING-T-59", "sexo": "M", "cat": "2", "raza": "", "ec": "3", "peso": "219"}, {"id": "10", "caravana": "ING-T-60", "sexo": "M", "cat": "2", "raza": "", "ec": "3", "peso": "220"}, {"id": "11", "caravana": "ING-T-61", "sexo": "H", "cat": "", "raza": "", "ec": "3,5", "peso": "211"}, {"id": "12", "caravana": "ING-T-62", "sexo": "H", "cat": "", "raza": "", "ec": "3,5", "peso": "212"}, {"id": "13", "caravana": "ING-T-63", "sexo": "H", "cat": "", "raza": "", "ec": "3,5", "peso": "213"}, {"id": "14", "caravana": "ING-T-64", "sexo": "H", "cat": "", "raza": "", "ec": "3,5", "peso": "214"}, {"id": "15", "caravana": "ING-T-65", "sexo": "H", "cat": "", "raza": "", "ec": "3,5", "peso": "215"}]
  ),
  sheetCase(
    "🔴 Varias categorías: Cat. faltante o imposible",
    "EN-20260928-0011 R1: ING-T-53 es macho y no tiene Cat. (puede ser Novillito o Torito), ING-T-58 dice Cat. 5 (la orden tiene 3) e ING-T-62 es hembra con Cat. 1 (Novillito). La revisión bloquea hasta corregirlas.",
    {"orden_ingreso": "EN-20260928-0011", "hoja_recepcion": "R1", "dte": "DTE-TEST-ING-009", "fecha_recepcion": "04/10/2026", "observaciones": "", "hoja_numero": 1, "hoja_total": 1},
    [{"id": "1", "caravana": "ING-T-51", "sexo": "M", "cat": "1", "raza": "", "ec": "3", "peso": "211"}, {"id": "2", "caravana": "ING-T-52", "sexo": "M", "cat": "1", "raza": "", "ec": "3", "peso": "212"}, {"id": "3", "caravana": "ING-T-53", "sexo": "M", "cat": "", "raza": "", "ec": "3", "peso": "213"}, {"id": "4", "caravana": "ING-T-54", "sexo": "M", "cat": "1", "raza": "", "ec": "3", "peso": "214"}, {"id": "5", "caravana": "ING-T-55", "sexo": "M", "cat": "1", "raza": "", "ec": "3", "peso": "215"}, {"id": "6", "caravana": "ING-T-56", "sexo": "M", "cat": "1", "raza": "", "ec": "3", "peso": "216"}, {"id": "7", "caravana": "ING-T-57", "sexo": "M", "cat": "2", "raza": "", "ec": "3", "peso": "217"}, {"id": "8", "caravana": "ING-T-58", "sexo": "M", "cat": "5", "raza": "", "ec": "3", "peso": "218"}, {"id": "9", "caravana": "ING-T-59", "sexo": "M", "cat": "2", "raza": "", "ec": "3", "peso": "219"}, {"id": "10", "caravana": "ING-T-60", "sexo": "M", "cat": "2", "raza": "", "ec": "3", "peso": "220"}, {"id": "11", "caravana": "ING-T-61", "sexo": "H", "cat": "", "raza": "", "ec": "3,5", "peso": "211"}, {"id": "12", "caravana": "ING-T-62", "sexo": "H", "cat": "1", "raza": "", "ec": "3,5", "peso": "212"}, {"id": "13", "caravana": "ING-T-63", "sexo": "H", "cat": "", "raza": "", "ec": "3,5", "peso": "213"}, {"id": "14", "caravana": "ING-T-64", "sexo": "H", "cat": "", "raza": "", "ec": "3,5", "peso": "214"}, {"id": "15", "caravana": "ING-T-65", "sexo": "H", "cat": "", "raza": "", "ec": "3,5", "peso": "215"}]
  ),
  sheetCase(
    "🟡 09 · Raza, pelaje y categoría escritas",
    "EN-20260928-0012 R1, escrita con palabras (horizontal): ING-T-71..80 con raza, pelaje y categoría como se escriben en la manga (Col., Braf, Negra). ING-T-79 es Angus, que la compra no declara: se recibe así y queda la novedad BREED_MISMATCH. Dos cabezas llegan después.",
    {"orden_ingreso": "EN-20260928-0012", "hoja_recepcion": "R1", "dte": "DTE-TEST-ING-010", "fecha_recepcion": "04/10/2026", "observaciones": "", "hoja_numero": 1, "hoja_total": 1},
    [{"id": "1", "caravana": "ING-T-71", "sexo": "", "cat": "Novillito", "raza": "Braford", "pelaje": "Colorado", "ec": "3", "peso": "221", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "2", "caravana": "ING-T-72", "sexo": "", "cat": "Novillito", "raza": "Braford", "pelaje": "Col.", "ec": "3,5", "peso": "218", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "3", "caravana": "ING-T-73", "sexo": "", "cat": "Torito", "raza": "Brangus", "pelaje": "Negro", "ec": "3", "peso": "240", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "4", "caravana": "ING-T-74", "sexo": "", "cat": "Novillito", "raza": "Braford", "pelaje": "Colorado", "ec": "3", "peso": "225", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "5", "caravana": "ING-T-75", "sexo": "", "cat": "Novillito", "raza": "Brangus", "pelaje": "Negro", "ec": "3,5", "peso": "215", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "6", "caravana": "ING-T-76", "sexo": "", "cat": "Torito", "raza": "Braf", "pelaje": "Colorado", "ec": "4", "peso": "246", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "7", "caravana": "ING-T-77", "sexo": "", "cat": "Novillito", "raza": "Brangus", "pelaje": "Negra", "ec": "3", "peso": "219", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "8", "caravana": "ING-T-78", "sexo": "", "cat": "Torito", "raza": "Braford", "pelaje": "Colorado", "ec": "3,5", "peso": "238", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "9", "caravana": "ING-T-79", "sexo": "", "cat": "Novillito", "raza": "Angus", "pelaje": "Negro", "ec": "3", "peso": "212", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "10", "caravana": "ING-T-80", "sexo": "", "cat": "Novillito", "raza": "Brangus", "pelaje": "Negro", "ec": "3", "peso": "223", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}]
  ),
  sheetCase(
    "🔴 09 · Raza escrita ambigua o incompleta",
    "EN-20260928-0012 R1: «Bra» puede ser Braford o Brangus, ING-T-72 no tiene pelaje (la orden tiene una sola línea Braford: se deduce), «Vaca» no es una categoría de la orden y hay un renglón con una lesión marcada y sin caravana. Al registrar, el servidor marca cada renglón y ofrece los candidatos con un clic.",
    {"orden_ingreso": "EN-20260928-0012", "hoja_recepcion": "R1", "dte": "DTE-TEST-ING-010", "fecha_recepcion": "04/10/2026", "observaciones": "", "hoja_numero": 1, "hoja_total": 1},
    [{"id": "1", "caravana": "ING-T-71", "sexo": "", "cat": "Novillito", "raza": "Bra", "pelaje": "Colorado", "ec": "3", "peso": "221", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "2", "caravana": "ING-T-72", "sexo": "", "cat": "Novillito", "raza": "Braford", "pelaje": "", "ec": "3", "peso": "218", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "3", "caravana": "ING-T-73", "sexo": "", "cat": "Vaca", "raza": "Brangus", "pelaje": "Negro", "ec": "3", "peso": "240", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "4", "caravana": "", "sexo": "", "cat": "", "raza": "", "pelaje": "", "ec": "", "peso": "", "lesion_ojo": "X", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "5", "caravana": "ING-T-75", "sexo": "", "cat": "Torito", "raza": "Brangus", "pelaje": "Negro", "ec": "3", "peso": "215", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}]
  ),
  sheetCase(
    "🟢 10 · Lesiones al arribo",
    "EN-20260928-0013 R1: llegan las 8 (ING-T-81..88); ING-T-82 con el ojo lesionado, ING-T-85 rengo (aplomo) e ING-T-87 con oreja y aplomo. Las lesiones quedan en su recepción, sin novedad.",
    {"orden_ingreso": "EN-20260928-0013", "hoja_recepcion": "R1", "dte": "DTE-TEST-ING-011", "fecha_recepcion": "04/10/2026", "observaciones": "", "hoja_numero": 1, "hoja_total": 1},
    [{"id": "1", "caravana": "ING-T-81", "sexo": "", "cat": "", "raza": "", "pelaje": "", "ec": "3", "peso": "181", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "2", "caravana": "ING-T-82", "sexo": "", "cat": "", "raza": "", "pelaje": "", "ec": "3", "peso": "176", "lesion_ojo": "X", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "3", "caravana": "ING-T-83", "sexo": "", "cat": "", "raza": "", "pelaje": "", "ec": "3,5", "peso": "184", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "4", "caravana": "ING-T-84", "sexo": "", "cat": "", "raza": "", "pelaje": "", "ec": "3", "peso": "179", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "5", "caravana": "ING-T-85", "sexo": "", "cat": "", "raza": "", "pelaje": "", "ec": "2,5", "peso": "168", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": "X"}, {"id": "6", "caravana": "ING-T-86", "sexo": "", "cat": "", "raza": "", "pelaje": "", "ec": "3", "peso": "183", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "7", "caravana": "ING-T-87", "sexo": "", "cat": "", "raza": "", "pelaje": "", "ec": "3", "peso": "175", "lesion_ojo": "", "lesion_oreja": "X", "lesion_aplomo": "X"}, {"id": "8", "caravana": "ING-T-88", "sexo": "", "cat": "", "raza": "", "pelaje": "", "ec": "3,5", "peso": "186", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}]
  ),
  sheetCase(
    "🟢 11 · Cat. por renglón (por código)",
    "EN-20260928-0011 R1, por código: los machos con su Cat. (1 Novillito, 2 Torito), las hembras sin (sólo pueden ser Vaquillona). Llegan las 15 y la orden se completa.",
    {"orden_ingreso": "EN-20260928-0011", "hoja_recepcion": "R1", "dte": "DTE-TEST-ING-009", "fecha_recepcion": "04/10/2026", "observaciones": "", "hoja_numero": 1, "hoja_total": 1},
    [{"id": "1", "caravana": "ING-T-51", "sexo": "M", "cat": "1", "raza": "", "pelaje": "", "ec": "3", "peso": "211", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "2", "caravana": "ING-T-52", "sexo": "M", "cat": "1", "raza": "", "pelaje": "", "ec": "3", "peso": "212", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "3", "caravana": "ING-T-53", "sexo": "M", "cat": "1", "raza": "", "pelaje": "", "ec": "3", "peso": "213", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "4", "caravana": "ING-T-54", "sexo": "M", "cat": "1", "raza": "", "pelaje": "", "ec": "3", "peso": "214", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "5", "caravana": "ING-T-55", "sexo": "M", "cat": "1", "raza": "", "pelaje": "", "ec": "3", "peso": "215", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "6", "caravana": "ING-T-56", "sexo": "M", "cat": "1", "raza": "", "pelaje": "", "ec": "3", "peso": "216", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "7", "caravana": "ING-T-57", "sexo": "M", "cat": "2", "raza": "", "pelaje": "", "ec": "3", "peso": "217", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "8", "caravana": "ING-T-58", "sexo": "M", "cat": "2", "raza": "", "pelaje": "", "ec": "3", "peso": "218", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "9", "caravana": "ING-T-59", "sexo": "M", "cat": "2", "raza": "", "pelaje": "", "ec": "3", "peso": "219", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "10", "caravana": "ING-T-60", "sexo": "M", "cat": "2", "raza": "", "pelaje": "", "ec": "3", "peso": "220", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "11", "caravana": "ING-T-61", "sexo": "H", "cat": "", "raza": "", "pelaje": "", "ec": "3,5", "peso": "211", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "12", "caravana": "ING-T-62", "sexo": "H", "cat": "", "raza": "", "pelaje": "", "ec": "3,5", "peso": "212", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "13", "caravana": "ING-T-63", "sexo": "H", "cat": "", "raza": "", "pelaje": "", "ec": "3,5", "peso": "213", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "14", "caravana": "ING-T-64", "sexo": "H", "cat": "", "raza": "", "pelaje": "", "ec": "3,5", "peso": "214", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}, {"id": "15", "caravana": "ING-T-65", "sexo": "H", "cat": "", "raza": "", "pelaje": "", "ec": "3,5", "peso": "215", "lesion_ojo": "", "lesion_oreja": "", "lesion_aplomo": ""}]
  ),
];
