import { CACT01_SHEET_CASES } from './cact01SheetCasePresets';
import { DEST01_SHEET_CASES } from './dest01SheetCasePresets';
import { PAR01_SHEET_CASES, PAR01_WHOLE_ORDER } from './par01SheetCasePresets';
import { ING02_PRESETS, ING02_SHEET_CASES } from './ing02SheetCasePresets';
import { ING03_SHEET_CASES } from './ing03SheetCasePresets';
import { SimulationPreset, SimulationScenario, SimulationTemplateInfo } from './types';

export const AVAILABLE_SIMULATION_TEMPLATES: SimulationTemplateInfo[] = [
  {
    code: 'ING-01',
    title: 'Ingreso de Compra Directa',
    category: 'ENTRY',
    categoryLabel: 'Ingreso Ganadero',
    color: '#16a34a',
    description: 'Registro de compra/ingreso de tropa, tipificación zootécnica (categoría, sexo, raza, dentición) y pesaje inicial.',
    availableScenarios: ['HAPPY_PATH', 'WARNINGS', 'REPAIR_ERROR'],
  },
  {
    code: 'ING-02',
    title: 'Orden de Ingreso de Hacienda Externa',
    category: 'ENTRY',
    categoryLabel: 'Ingreso Ganadero',
    color: '#0d9488',
    description: 'Documento de una compra de hacienda externa: proveedor, establecimiento, subasta, categorías con sus cabezas, sexo, razas, pesos, estado, edad, sabe comer, garrapata y desbaste. Crea la orden en espera de DTE.',
    availableScenarios: ['HAPPY_PATH', 'WARNINGS', 'REPAIR_ERROR', 'SHEET_CASES'],
  },
  {
    code: 'ING-03',
    title: 'Recepción de DTE (anexo de ING-02)',
    category: 'ENTRY',
    categoryLabel: 'Ingreso Ganadero',
    color: '#0f766e',
    description: 'Hoja de recepción de un DTE: las caravanas en tránsito marcadas en la manga (llegó / no llega / peso) y animales que llegan sin figurar en el DTE. Se resuelve contra la orden y registra la recepción.',
    availableScenarios: ['HAPPY_PATH', 'WARNINGS', 'REPAIR_ERROR', 'SHEET_CASES'],
  },
  {
    code: 'TOR-01',
    title: 'Revisación Andrológica y Muestreo en Manga',
    category: 'REPRODUCTIVE',
    categoryLabel: 'Reproductivo / Manga',
    color: '#0284c7',
    description: 'Evaluación andrológica integral (CE, CC, aplomos, líbido) y doble muestreo de raspaje prepucial (ETS) y serología de sangre.',
    availableScenarios: ['HAPPY_PATH', 'WARNINGS', 'REPAIR_ERROR'],
  },
  {
    code: 'LSER-01',
    title: 'Conformación de Lote de Servicio — Toro Único',
    category: 'REPRODUCTIVE',
    categoryLabel: 'Entore / Servicio',
    color: '#9333ea',
    description: 'Constitución de lote de entore con un toro exclusivo en cabecera y vientres asignados en tabla. Genera lote, orden de servicio y movimientos.',
    availableScenarios: ['HAPPY_PATH', 'WARNINGS', 'REPAIR_ERROR'],
  },
  {
    code: 'DEST-01',
    title: 'Destete y Conformación de Lote de Destete',
    category: 'WEANING',
    categoryLabel: 'Destete / Desmadre',
    color: '#ea580c',
    description: 'Desmadre de crías al pie hacia un lote de destete o uno por cría, nuevo o existente, con peso de balanza y C/S nueva. Cumple una orden de destete o crea la suya. Soporta múltiples hojas.',
    availableScenarios: ['HAPPY_PATH', 'PER_ANIMAL', 'WARNINGS', 'MULTI_PAGE', 'REPAIR_ERROR', 'SHEET_CASES'],
  },
  {
    code: 'CACT-01',
    title: 'Cambio de Actividad de Hacienda',
    category: 'ACTIVITY',
    categoryLabel: 'Cambio de Actividad',
    color: '#0369a1',
    description: 'Movimiento de hacienda entre actividades con pesaje en la manga. Una sola actividad de destino por planilla; admite un destino único o un destino por animal, en varias hojas.',
    availableScenarios: ['HAPPY_PATH', 'PER_ANIMAL', 'TRANSFER_ORDER', 'WARNINGS', 'MULTI_PAGE', 'REPAIR_ERROR', 'SHEET_CASES'],
  },
  {
    code: 'REP-01',
    title: 'Planilla de Tacto y Ecografía',
    category: 'REPRODUCTIVE',
    categoryLabel: 'Diagnóstico Gestación',
    color: '#db2777',
    description: 'Diagnóstico de preñez a campo (Preñada / Vacía) con estimación de estadio (Cabeza, Cuerpo, Cola) para separación de rodeo.',
    availableScenarios: ['HAPPY_PATH', 'WARNINGS', 'REPAIR_ERROR'],
  },
  {
    code: 'PAR-01',
    title: 'Planilla de Parición',
    category: 'REPRODUCTIVE',
    categoryLabel: 'Maternidad / Partos',
    color: '#e11d48',
    description: 'Recorrida de parición: resultado de cada vientre (parió, nacido muerto, aborto), caravana, sexo, peso, raza y fecha de la cría, y los partos fuera de la orden. Cumple una orden de parición en varias recorridas; la cría queda en el lote de su madre.',
    availableScenarios: ['HAPPY_PATH', 'WARNINGS', 'MULTI_PAGE', 'REPAIR_ERROR', 'SHEET_CASES'],
  },
  {
    code: 'MON-01',
    title: 'Servicio de Monta y Entore a Campo',
    category: 'REPRODUCTIVE',
    categoryLabel: 'Monta Natural',
    color: '#7c3aed',
    description: 'Planilla de asignación zootécnica de vientres en entore con padrillos, condición corporal y registro de montas observadas.',
    availableScenarios: ['HAPPY_PATH', 'WARNINGS'],
  },
  {
    code: 'OP-01',
    title: 'Control Mensual de Lotes (Pesaje)',
    category: 'WEIGHT',
    categoryLabel: 'Control de Peso',
    color: '#0d9488',
    description: 'Pesaje periódico de rutina para evolución de ganancia diaria media (GMD) y monitoreo de condición corporal en recría.',
    availableScenarios: ['HAPPY_PATH', 'WARNINGS'],
  },
  {
    code: 'OP-02',
    title: 'Transferencia a Invernada',
    category: 'ACTIVITY',
    categoryLabel: 'Cambio de Actividad',
    color: '#ca8a04',
    description: 'Movimiento operacional de tropas que finalizan la recría y pasan a terminación a pasto o feedlot.',
    availableScenarios: ['HAPPY_PATH', 'WARNINGS'],
  },
];

/**
 * Catalog of high-fidelity simulation presets organized by Template Code and Scenario.
 */
/**
 * Partial per template: a scenario only exists where it means something. PER_ANIMAL, for
 * instance, is a CACT-01 matter — no other template splits a troop into several destinations —
 * and `getSimulationPreset` already falls back to the happy path for anything missing.
 */
export const SIMULATION_PRESETS: Record<string, Partial<Record<SimulationScenario, SimulationPreset>>> = {
  'ING-01': {
    HAPPY_PATH: {
      templateCode: 'ING-01',
      scenario: 'HAPPY_PATH',
      scenarioLabel: '🟢 Flujo Válido Estándar (8 Animales)',
      scenarioDescription: 'Tropa balanceada con categorías, razas, dentición y pesajes realistas. Pasa validación al 100%.',
      templateTitle: 'Ingreso de Compra Directa',
      category: 'ENTRY',
      context: {
        batch_name: 'LOTE-ING-2026-01',
        activity_name: 'CRIA',
        entry_date: new Date().toISOString().slice(0, 10),
        provider_name: 'Estancia Las Lilas S.A.',
        provider_cuit: '30-71234567-9',
        provider_renspa: '02.123.4.56789/00',
        guia_dte: 'DTE-884920',
        observaciones: 'Tropa ingresada en perfecto estado. Inspección sanitaria sin novedades.',
      },
      rows: [
        { id: 1, caravana: 'AR-101', category: 'Vaca de Cría', sex: 'H', breed: 'Angus Negro', teeth: 6, entry_weight: 435.0, observations: 'CC 3.5, preñada cabeza', confidence: 0.99 },
        { id: 2, caravana: 'AR-102', category: 'Vaca de Cría', sex: 'H', breed: 'Angus Colorado', teeth: 4, entry_weight: 418.0, observations: 'CC 3.0, con ternero', confidence: 0.98 },
        { id: 3, caravana: 'AR-103', category: 'Ternero', sex: 'M', breed: 'Brangus', teeth: 0, entry_weight: 165.0, observations: 'Al pie de la madre', confidence: 0.99 },
        { id: 4, caravana: 'AR-104', category: 'Ternera', sex: 'H', breed: 'Hereford', teeth: 0, entry_weight: 154.0, observations: 'Al pie de la madre', confidence: 0.97 },
        { id: 5, caravana: 'AR-105', category: 'Vaquillona Reposición', sex: 'H', breed: 'Angus', teeth: 2, entry_weight: 290.0, observations: 'Apta entore', confidence: 0.98 },
        { id: 6, caravana: 'AR-106', category: 'Vaquillona', sex: 'H', breed: 'Braford', teeth: 2, entry_weight: 298.0, observations: 'Sanidad completa', confidence: 0.96 },
        { id: 7, caravana: 'AR-107', category: 'Toro', sex: 'M', breed: 'Angus Negro', teeth: 6, entry_weight: 685.0, observations: 'Toro padre probado', confidence: 0.99 },
        { id: 8, caravana: 'AR-108', category: 'Toro', sex: 'M', breed: 'Brangus', teeth: 6, entry_weight: 645.0, observations: 'Evaluación andrológica OK', confidence: 0.99 },
      ],
    },
    WARNINGS: {
      templateCode: 'ING-01',
      scenario: 'WARNINGS',
      scenarioLabel: '🟡 Flujo con Advertencias (Duplicados & Peso Cero)',
      scenarioDescription: 'Simula errores frecuentes de lectura en manga: caravana duplicada (AR-102) y animal con peso 0 kg.',
      templateTitle: 'Ingreso de Compra Directa',
      category: 'ENTRY',
      context: {
        batch_name: 'LOTE-ING-ALERTAS',
        activity_name: 'CRIA',
        entry_date: new Date().toISOString().slice(0, 10),
        provider_name: 'Cabaña El Ombú',
        provider_cuit: '30-66442211-5',
        provider_renspa: '02.999.8.77777/01',
        guia_dte: 'DTE-993112',
        observaciones: 'Revisar balanza: pesajes con lecturas dudosas en manga.',
      },
      rows: [
        { id: 1, caravana: 'AR-101', category: 'Vaca de Cría', sex: 'H', breed: 'Angus', teeth: 4, entry_weight: 420.0, observations: '', confidence: 0.98 },
        { id: 2, caravana: 'AR-102', category: 'Vaca de Cría', sex: 'H', breed: 'Angus', teeth: 6, entry_weight: 430.0, observations: 'Primera lectura', confidence: 0.95 },
        { id: 3, caravana: 'AR-102', category: 'Vaca de Cría', sex: 'H', breed: 'Angus', teeth: 6, entry_weight: 428.0, observations: 'Caravana duplicada detectada', confidence: 0.94 },
        { id: 4, caravana: 'AR-104', category: 'Novillito', sex: 'M', breed: 'Hereford', teeth: 2, entry_weight: 0.0, observations: 'No pisó la celda de carga', confidence: 0.90 },
      ],
    },
    REPAIR_ERROR: {
      templateCode: 'ING-01',
      scenario: 'REPAIR_ERROR',
      scenarioLabel: '🔴 Flujo con Errores Críticos (Caravanas Vacías)',
      scenarioDescription: 'Simula filas manuscritas ilegibles donde falta la caravana o el lote de destino, bloqueando la confirmación. El chip rojo del encabezado abre la guía de errores.',
      templateTitle: 'Ingreso de Compra Directa',
      category: 'ENTRY',
      context: {
        batch_name: '',
        activity_name: 'RECRIA',
        entry_date: new Date().toISOString().slice(0, 10),
        provider_name: 'Proveedor Sin Identificar',
        provider_cuit: '',
        provider_renspa: '',
        guia_dte: '',
        observaciones: 'Planilla incompleta y manchada.',
      },
      rows: [
        { id: 1, caravana: '', category: 'Vaca', sex: 'H', breed: 'Cruza', teeth: 4, entry_weight: 400.0, observations: 'Caravana borrosa', confidence: 0.35 },
        { id: 2, caravana: 'AR-202', category: '', sex: 'M', breed: 'Angus', teeth: 2, entry_weight: 310.0, observations: '', confidence: 0.90 },
      ],
    },
    MULTI_PAGE: {} as any,
  },

  'TOR-01': {
    HAPPY_PATH: {
      templateCode: 'TOR-01',
      scenario: 'HAPPY_PATH',
      scenarioLabel: '🟢 Torada 100% Apta (12 Toros)',
      scenarioDescription: '12 reproductores con CE > 32 cm, CC óptima, raspajes y serología completos con tubos individuales.',
      templateTitle: 'Revisación Andrológica y Muestreo en Manga',
      category: 'REPRODUCTIVE',
      context: {
        farm_name: 'Estancia La Juanita',
        renspa: '02.001.0.00001/01',
        veterinarian_name: 'Dr. Esteban Rossi',
        veterinarian_license: 'MP: 4892-BA',
        sample_round: 1,
        evaluation_date: new Date().toISOString().slice(0, 10),
        observaciones: 'Toros evaluados en manga con cepo hidráulico. Excelente condición seminal y física.',
      },
      rows: [
        { id: 1, caravana: 'TR-001', ce_cm: 37.5, bcs: 3.5, libido: 'ALTA', aplomos: 'Correctos', scrape_collected: true, scrape_tube: 'R-01', serology_collected: true, serology_tube: 'S-01', physical_verdict: 'A', observations: 'Excelente conformación', confidence: 0.99 },
        { id: 2, caravana: 'TR-002', ce_cm: 35.0, bcs: 3.0, libido: 'M', aplomos: 'Buenos', scrape_collected: true, scrape_tube: 'R-02', serology_collected: true, serology_tube: 'S-02', physical_verdict: 'A', observations: 'Rodeo general', confidence: 0.98 },
        { id: 3, caravana: 'TR-003', ce_cm: 36.0, bcs: 3.5, libido: 'MEDIA', aplomos: 'Correctos', scrape_collected: true, scrape_tube: 'R-03', serology_collected: true, serology_tube: 'S-03', physical_verdict: 'A', observations: 'Buen prepucio', confidence: 0.97 },
        { id: 4, caravana: 'TR-004', ce_cm: 34.5, bcs: 3.0, libido: 'M', aplomos: 'Correctos', scrape_collected: true, scrape_tube: 'R-04', serology_collected: true, serology_tube: 'S-04', physical_verdict: 'A', observations: 'Sin novedades', confidence: 0.96 },
        { id: 5, caravana: 'TR-005', ce_cm: 38.0, bcs: 4.0, libido: 'ALTA', aplomos: 'Correctos', scrape_collected: true, scrape_tube: 'R-05', serology_collected: true, serology_tube: 'S-05', physical_verdict: 'A', observations: 'Toro padre de cabaña', confidence: 0.99 },
        { id: 6, caravana: 'TR-006', ce_cm: 33.5, bcs: 3.0, libido: 'M', aplomos: 'Buenos', scrape_collected: true, scrape_tube: 'R-06', serology_collected: true, serology_tube: 'S-06', physical_verdict: 'A', observations: 'Torito 2 años', confidence: 0.95 },
        { id: 7, caravana: 'TR-007', ce_cm: 35.5, bcs: 3.5, libido: 'A', aplomos: 'Correctos', scrape_collected: true, scrape_tube: 'R-07', serology_collected: true, serology_tube: 'S-07', physical_verdict: 'A', observations: 'Testículos simétricos', confidence: 0.98 },
        { id: 8, caravana: 'TR-008', ce_cm: 36.0, bcs: 3.5, libido: 'MEDIA', aplomos: 'Correctos', scrape_collected: true, scrape_tube: 'R-08', serology_collected: true, serology_tube: 'S-08', physical_verdict: 'A', observations: 'Destino entore 1', confidence: 0.97 },
        { id: 9, caravana: 'TR-009', ce_cm: 34.0, bcs: 3.0, libido: 'M', aplomos: 'Buenos', scrape_collected: true, scrape_tube: 'R-09', serology_collected: true, serology_tube: 'S-09', physical_verdict: 'A', observations: 'Correcto', confidence: 0.96 },
        { id: 10, caravana: 'TR-010', ce_cm: 37.0, bcs: 3.5, libido: 'ALTA', aplomos: 'Correctos', scrape_collected: true, scrape_tube: 'R-10', serology_collected: true, serology_tube: 'S-10', physical_verdict: 'A', observations: 'Plantel superior', confidence: 0.99 },
        { id: 11, caravana: 'TR-011', ce_cm: 35.0, bcs: 3.0, libido: 'M', aplomos: 'Correctos', scrape_collected: true, scrape_tube: 'R-11', serology_collected: true, serology_tube: 'S-11', physical_verdict: 'A', observations: 'Repetir R2 en 15 d', confidence: 0.98 },
        { id: 12, caravana: 'TR-012', ce_cm: 36.5, bcs: 3.5, libido: 'A', aplomos: 'Correctos', scrape_collected: true, scrape_tube: 'R-12', serology_collected: true, serology_tube: 'S-12', physical_verdict: 'A', observations: 'Lote vaquillonas', confidence: 0.99 },
      ],
    },
    WARNINGS: {
      templateCode: 'TOR-01',
      scenario: 'WARNINGS',
      scenarioLabel: '🟡 Flujo con Advertencias Veterinarias (CE < 28 cm & Rechazo)',
      scenarioDescription: 'Dispara alertas zootécnicas: toro con hipoplasia testicular (CE 26.5 cm), raspaje sin tubo y dictamen Rechazo.',
      templateTitle: 'Revisación Andrológica y Muestreo en Manga',
      category: 'REPRODUCTIVE',
      context: {
        farm_name: 'Establecimiento San Pedro',
        renspa: '02.441.2.00311/00',
        veterinarian_name: 'Dr. Esteban Rossi',
        veterinarian_license: 'MP: 4892-BA',
        sample_round: 1,
        evaluation_date: new Date().toISOString().slice(0, 10),
        observaciones: 'Atención: Se detectó 1 toro con hipoplasia testicular y lesión podal.',
      },
      rows: [
        { id: 1, caravana: 'TR-101', ce_cm: 36.0, bcs: 3.5, libido: 'ALTA', aplomos: 'Correctos', scrape_collected: true, scrape_tube: 'R-01', serology_collected: true, serology_tube: 'S-01', physical_verdict: 'A', observations: 'Apto', confidence: 0.98 },
        { id: 2, caravana: 'TR-102', ce_cm: 26.5, bcs: 2.5, libido: 'BAJA', aplomos: 'Garrones rectos', scrape_collected: true, scrape_tube: '', serology_collected: true, serology_tube: 'S-02', physical_verdict: 'R', observations: 'Hipoplasia testicular. RECHAZO.', confidence: 0.95 },
        { id: 3, caravana: 'TR-103', ce_cm: 27.5, bcs: 3.0, libido: 'MEDIA', aplomos: 'Infosura podal', scrape_collected: false, scrape_tube: '', serology_collected: true, serology_tube: 'S-03', physical_verdict: 'T', observations: 'En tratamiento podológico', confidence: 0.96 },
      ],
    },
    REPAIR_ERROR: {
      templateCode: 'TOR-01',
      scenario: 'REPAIR_ERROR',
      scenarioLabel: '🔴 Flujo con Errores (Toros sin Identificación)',
      scenarioDescription: 'Simula filas con campos mandatorios vacíos que impiden guardar la planilla andrológica. El chip rojo del encabezado abre la guía de errores.',
      templateTitle: 'Revisación Andrológica y Muestreo en Manga',
      category: 'REPRODUCTIVE',
      context: {
        farm_name: '',
        renspa: '',
        veterinarian_name: '',
        veterinarian_license: '',
        sample_round: 1,
        evaluation_date: new Date().toISOString().slice(0, 10),
        observaciones: 'Planilla sin firma ni veterinario.',
      },
      rows: [
        { id: 1, caravana: '', ce_cm: 35.0, bcs: 3.0, libido: 'M', aplomos: 'Buenos', scrape_collected: true, scrape_tube: 'R-01', serology_collected: true, serology_tube: 'S-01', physical_verdict: 'A', observations: 'Sin caravana visible', confidence: 0.4 },
      ],
    },
    MULTI_PAGE: {} as any,
  },

  'LSER-01': {
    HAPPY_PATH: {
      templateCode: 'LSER-01',
      scenario: 'HAPPY_PATH',
      scenarioLabel: '🟢 Flujo Válido (Toro Anthony-004 + 10 Vientres)',
      scenarioDescription: 'Entore de vaquillonas con toro exclusivo verificado, fechas de servicio y vientres registrados.',
      templateTitle: 'Conformación de Lote de Servicio — Toro Único',
      category: 'REPRODUCTIVE',
      context: {
        lote: 'Entore Vaquillonas Toro 004',
        toro_caravana: 'ANTHONY-TORO-TEST-004',
        planned_start_date: new Date().toISOString().slice(0, 10),
        planned_end_date: new Date(Date.now() + 60 * 24 * 3600 * 1000).toISOString().slice(0, 10),
        responsable: 'Encargado de manga',
        observaciones: 'Lote homogéneo de vaquillonas para entore de 60 días.',
      },
      rows: [
        { id: 1, caravana: 'VQ-101', observations: 'CC 3.5, excelente desarrollo', confidence: 0.98 },
        { id: 2, caravana: 'VQ-102', observations: 'CC 3.5', confidence: 0.97 },
        { id: 3, caravana: 'VQ-103', observations: 'CC 3.0', confidence: 0.98 },
        { id: 4, caravana: 'VQ-104', observations: 'CC 3.5', confidence: 0.96 },
        { id: 5, caravana: 'VQ-105', observations: 'CC 3.5', confidence: 0.99 },
        { id: 6, caravana: 'VQ-106', observations: 'CC 3.0', confidence: 0.97 },
        { id: 7, caravana: 'VQ-107', observations: 'CC 3.5', confidence: 0.98 },
        { id: 8, caravana: 'VQ-108', observations: 'CC 3.5', confidence: 0.99 },
        { id: 9, caravana: 'VQ-109', observations: 'CC 3.0', confidence: 0.95 },
        { id: 10, caravana: 'VQ-110', observations: 'CC 3.5', confidence: 0.98 },
      ],
    },
    WARNINGS: {
      templateCode: 'LSER-01',
      scenario: 'WARNINGS',
      scenarioLabel: '🟡 Flujo con Advertencias (Caravanas Duplicadas)',
      scenarioDescription: 'Vientre registrado dos veces por error de escritura en manga.',
      templateTitle: 'Conformación de Lote de Servicio — Toro Único',
      category: 'REPRODUCTIVE',
      context: {
        lote: 'Entore Lote 2',
        toro_caravana: 'ANTHONY-TORO-TEST-004',
        planned_start_date: new Date().toISOString().slice(0, 10),
        responsable: 'Manga',
        observaciones: 'Revisar duplicados.',
      },
      rows: [
        { id: 1, caravana: 'VQ-101', observations: '', confidence: 0.98 },
        { id: 2, caravana: 'VQ-102', observations: '', confidence: 0.97 },
        { id: 3, caravana: 'VQ-102', observations: 'Duplicada en manga', confidence: 0.95 },
      ],
    },
    REPAIR_ERROR: {
      templateCode: 'LSER-01',
      scenario: 'REPAIR_ERROR',
      scenarioLabel: '🔴 Flujo de Reparación (Vientre No Registrado)',
      scenarioDescription: 'Simula un fallo transaccional 422 con vientres no encontrados para activar y verificar Lser01RepairDialog y la guía de errores de su barra.',
      templateTitle: 'Conformación de Lote de Servicio — Toro Único',
      category: 'REPRODUCTIVE',
      context: {
        lote: 'Entore Vaquillonas Con Errores',
        toro_caravana: 'TORO-INEXISTENTE-999',
        planned_start_date: new Date().toISOString().slice(0, 10),
        responsable: 'Operador Manga',
        observaciones: 'Prueba de bloqueo por todo o nada.',
      },
      rows: [
        { id: 1, caravana: 'VIENTRE-INEXISTENTE-01', observations: '', confidence: 0.90 },
        { id: 2, caravana: 'VIENTRE-INEXISTENTE-02', observations: '', confidence: 0.90 },
      ],
      mockErrors: {
        headerErrors: [{ field: 'toro_caravana', code: 'bull_not_found', message: 'El toro no existe en el establecimiento' }],
        rowErrors: [
          { row_index: 0, caravana: 'VIENTRE-INEXISTENTE-01', errors: [{ code: 'not_found', message: 'Animal no hallado en el rodeo' }] },
          { row_index: 1, caravana: 'VIENTRE-INEXISTENTE-02', errors: [{ code: 'not_found', message: 'Animal no hallado en el rodeo' }] },
        ],
      },
    },
    MULTI_PAGE: {} as any,
  },

  'CACT-01': {
    // Against the order seeded by Cact01ActivityChangeScanTestSeeder (017..024 to "Test CACT
    // Recría"): four of its eight head, so the load leaves it PARTIAL and names who is missing.
    TRANSFER_ORDER: {
      templateCode: 'CACT-01',
      scenario: 'TRANSFER_ORDER',
      scenarioLabel: '🔵 Con orden TR-20260615-0001, tanda parcial (4 de 8)',
      scenarioDescription:
        'Planilla impresa desde una orden de transferencia: el código del encabezado resuelve la orden, la carga hereda su lote de origen y su destino, y al confirmar queda PARCIAL con los cuatro animales que faltan. Requiere Cact01ActivityChangeScanTestSeeder.',
      templateTitle: 'Cambio de Actividad de Hacienda',
      category: 'ACTIVITY',
      context: {
        actividad_origen: 'Cría',
        actividad_destino: 'Recría',
        lote_origen: 'Test CACT Cría',
        lote_destino: 'Test CACT Recría',
        fecha_movimiento: new Date().toISOString().slice(0, 10),
        sistema_manejo: 'PASTURA',
        total_cabezas: 4,
        peso_total: 1296,
        responsable: 'Encargado de manga',
        hoja_numero: 1,
        hoja_total: 1,
        orden_transferencia: 'TR-20260615-0001',
        observaciones: 'Sólo pasaron cuatro por la manga.',
      },
      rows: [
        { id: '1', caravana: 'GRO-001-CAR-017', peso_actual: '318.0', sexo: 'M', categoria: 'Ternero', dientes: '2D', lote_destino: '', observations: '' },
        { id: '2', caravana: 'GRO-001-CAR-018', peso_actual: '322.0', sexo: 'H', categoria: 'Ternero', dientes: '2D', lote_destino: '', observations: '' },
        { id: '3', caravana: 'GRO-001-CAR-019', peso_actual: '326.0', sexo: 'M', categoria: 'Ternero', dientes: '2D', lote_destino: '', observations: '' },
        { id: '4', caravana: 'GRO-001-CAR-020', peso_actual: '330.0', sexo: 'M', categoria: 'Ternero', dientes: '2D', lote_destino: '', observations: '' },
      ],
    },
    HAPPY_PATH: {
      templateCode: 'CACT-01',
      scenario: 'HAPPY_PATH',
      scenarioLabel: '🟢 Cría → Recría, destino único (12 cabezas)',
      scenarioDescription: 'Tropa completa que pasa de Cría a un lote de Recría nuevo a corral, con peso y dentición de todos y los totales del recuadro cerrando.',
      templateTitle: 'Cambio de Actividad de Hacienda',
      category: 'ACTIVITY',
      context: {
        actividad_origen: 'Cría',
        actividad_destino: 'Recría',
        lote_origen: 'Rodeo Cría 1',
        lote_destino: 'Recría Otoño 2026',
        fecha_movimiento: new Date().toISOString().slice(0, 10),
        sistema_manejo: 'CORRAL',
        total_cabezas: 12,
        peso_total: 2928,
        responsable: 'Encargado de manga',
        hoja_numero: 1,
        hoja_total: 1,
        observaciones: 'Tropa completa. Se pesa a la salida del potrero.',
      },
      rows: [
        { id: '1', caravana: 'CA-301', peso_actual: '240.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: '', observations: '' },
        { id: '2', caravana: 'CA-302', peso_actual: '248.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: '', observations: '' },
        { id: '3', caravana: 'CA-303', peso_actual: '236.5', sexo: 'H', categoria: 'Ternera', dientes: 'DL', lote_destino: '', observations: '' },
        { id: '4', caravana: 'CA-304', peso_actual: '252.0', sexo: 'M', categoria: 'Ternero', dientes: '2D', lote_destino: '', observations: '' },
        { id: '5', caravana: 'CA-305', peso_actual: '229.0', sexo: 'H', categoria: 'Ternera', dientes: 'DL', lote_destino: '', observations: '' },
        { id: '6', caravana: 'CA-306', peso_actual: '245.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: '', observations: '' },
        { id: '7', caravana: 'CA-307', peso_actual: '251.5', sexo: 'M', categoria: 'Ternero', dientes: '2D', lote_destino: '', observations: '' },
        { id: '8', caravana: 'CA-308', peso_actual: '238.0', sexo: 'H', categoria: 'Ternera', dientes: 'DL', lote_destino: '', observations: '' },
        { id: '9', caravana: 'CA-309', peso_actual: '244.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: '', observations: '' },
        { id: '10', caravana: 'CA-310', peso_actual: '247.0', sexo: 'H', categoria: 'Ternera', dientes: 'DL', lote_destino: '', observations: '' },
        { id: '11', caravana: 'CA-311', peso_actual: '253.0', sexo: 'M', categoria: 'Ternero', dientes: '2D', lote_destino: '', observations: '' },
        { id: '12', caravana: 'CA-312', peso_actual: '244.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: '', observations: '' },
      ],
    },
    PER_ANIMAL: {
      templateCode: 'CACT-01',
      scenario: 'PER_ANIMAL',
      scenarioLabel: '🟢 Destino por animal, tres lotes de Recría (columna M)',
      scenarioDescription:
        'Una sola actividad de destino —Recría— repartida en tres lotes: dos existentes y uno a crear. Cada fila lleva su lote y su celda M, coherente para todas las filas del mismo lote. Al escanear sólo queda por preguntar el tipo del lote nuevo.',
      templateTitle: 'Cambio de Actividad de Hacienda',
      category: 'ACTIVITY',
      context: {
        actividad_origen: 'Cría',
        actividad_destino: 'Recría',
        lote_origen: 'Rodeo Cría 1',
        lote_destino: '',
        fecha_movimiento: new Date().toISOString().slice(0, 10),
        // Nothing to mark here: with a destination per animal the letter lives in the M column.
        sistema_manejo: '',
        total_cabezas: 9,
        peso_total: 2223,
        responsable: 'Encargado de manga',
        hoja_numero: 1,
        hoja_total: 1,
        observaciones: 'Se aparta por sexo y estado. Todos los destinos son lotes de Recría.',
      },
      rows: [
        { id: '1', caravana: 'CA-501', peso_actual: '246.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: 'Recría Norte', manejo: 'P', observations: '' },
        { id: '2', caravana: 'CA-502', peso_actual: '251.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: 'Recría Norte', manejo: 'P', observations: '' },
        { id: '3', caravana: 'CA-503', peso_actual: '243.0', sexo: 'M', categoria: 'Ternero', dientes: '2D', lote_destino: 'Recría Norte', manejo: 'P', observations: '' },
        { id: '4', caravana: 'CA-504', peso_actual: '238.0', sexo: 'H', categoria: 'Ternera', dientes: 'DL', lote_destino: 'Recría Sur', manejo: 'P', observations: '' },
        { id: '5', caravana: 'CA-505', peso_actual: '241.0', sexo: 'H', categoria: 'Ternera', dientes: 'DL', lote_destino: 'Recría Sur', manejo: 'P', observations: '' },
        { id: '6', caravana: 'CA-506', peso_actual: '235.0', sexo: 'H', categoria: 'Ternera', dientes: 'DL', lote_destino: 'Recría Sur', manejo: 'P', observations: '' },
        { id: '7', caravana: 'CA-507', peso_actual: '258.0', sexo: 'M', categoria: 'Ternero', dientes: '2D', lote_destino: 'Recría Corral Nuevo', manejo: 'C', observations: 'Lote a crear, a corral' },
        { id: '8', caravana: 'CA-508', peso_actual: '256.0', sexo: 'M', categoria: 'Ternero', dientes: '2D', lote_destino: 'Recría Corral Nuevo', manejo: 'C', observations: 'Lote a crear, a corral' },
        { id: '9', caravana: 'CA-509', peso_actual: '255.0', sexo: 'M', categoria: 'Ternero', dientes: '2D', lote_destino: 'Recría Corral Nuevo', manejo: 'C', observations: 'Lote a crear, a corral' },
      ],
    },
    WARNINGS: {
      templateCode: 'CACT-01',
      scenario: 'WARNINGS',
      scenarioLabel: '🟡 Destino por animal + avisos que no bloquean',
      scenarioDescription:
        'Tres destinos de la misma actividad en la columna por fila, dos animales sin peso, uno con el sexo cambiado, uno con dentición menor a la registrada, el peso total del recuadro desfasado y una celda M que contradice el manejo declarado del lote existente.',
      templateTitle: 'Cambio de Actividad de Hacienda',
      category: 'ACTIVITY',
      context: {
        actividad_origen: 'Invernada',
        actividad_destino: 'Recría',
        lote_origen: 'Rodeo Cría 1',
        lote_destino: '',
        fecha_movimiento: new Date().toISOString().slice(0, 10),
        sistema_manejo: '',
        total_cabezas: 6,
        peso_total: 1800,
        responsable: 'Encargado de manga',
        hoja_numero: 1,
        hoja_total: 1,
        observaciones: 'Se reparte la tropa en tres destinos según destino comercial.',
      },
      rows: [
        { id: '1', caravana: 'CA-401', peso_actual: '262.0', sexo: 'M', categoria: 'Novillito', dientes: '2D', lote_destino: 'Recría Norte', manejo: 'C', observations: 'La M dice corral y el lote está declarado a pastura' },
        { id: '2', caravana: 'CA-402', peso_actual: '', sexo: 'M', categoria: 'Novillito', dientes: '', lote_destino: 'Recría Norte', manejo: 'C', observations: 'No pasó por balanza' },
        { id: '3', caravana: 'CA-403', peso_actual: '258.0', sexo: 'H', categoria: 'Vaquillona', dientes: '2D', lote_destino: 'Recría Sur', manejo: 'P', observations: 'El papel dice H, el sistema dice M' },
        { id: '4', caravana: 'CA-404', peso_actual: '', sexo: 'M', categoria: 'Novillito', dientes: '2D', lote_destino: 'Recría Sur', manejo: 'P', observations: 'No pasó por balanza' },
        { id: '5', caravana: 'CA-405', peso_actual: '271.0', sexo: 'M', categoria: 'Novillito', dientes: 'DL', lote_destino: 'Recría Este', manejo: '', observations: 'Dentición leída menor que la registrada; celda M en blanco' },
        { id: '6', caravana: 'CA-406', peso_actual: '266.0', sexo: 'M', categoria: 'Novillito', dientes: '4D', lote_destino: 'Recría Este', manejo: '', observations: '' },
      ],
    },
    MULTI_PAGE: {
      templateCode: 'CACT-01',
      scenario: 'MULTI_PAGE',
      scenarioLabel: '📄 Tropa grande en 2 hojas',
      scenarioDescription: 'Dos hojas del mismo movimiento que se unen por hoja_numero y se confirman juntas.',
      templateTitle: 'Cambio de Actividad de Hacienda',
      category: 'ACTIVITY',
      context: {
        actividad_origen: 'Cría',
        actividad_destino: 'Recría',
        lote_origen: 'Rodeo Cría General',
        lote_destino: 'Recría General 2026',
        fecha_movimiento: new Date().toISOString().slice(0, 10),
        sistema_manejo: 'CORRAL',
        total_cabezas: 7,
        peso_total: 1729,
        responsable: 'Encargado de manga',
        hoja_numero: 1,
        hoja_total: 2,
        observaciones: 'Tropa grande escaneada en dos hojas consecutivas.',
      },
      rows: [
        { id: '1', caravana: 'CA-H1-01', peso_actual: '243.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: '', observations: 'Hoja 1' },
        { id: '2', caravana: 'CA-H1-02', peso_actual: '251.0', sexo: 'H', categoria: 'Ternera', dientes: 'DL', lote_destino: '', observations: 'Hoja 1' },
        { id: '3', caravana: 'CA-H1-03', peso_actual: '239.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: '', observations: 'Hoja 1' },
        { id: '4', caravana: 'CA-H1-04', peso_actual: '256.0', sexo: 'M', categoria: 'Ternero', dientes: '2D', lote_destino: '', observations: 'Hoja 1' },
      ],
      pages: [
        {
          key: 'page-1',
          fileName: 'planilla_cact01_hoja_1.svg',
          hojaNumero: 1,
          hojaTotal: 2,
          metadata: {
            actividad_origen: 'Cría',
            actividad_destino: 'Recría',
            lote_origen: 'Rodeo Cría General',
            lote_destino: 'Recría General 2026',
            fecha_movimiento: new Date().toISOString().slice(0, 10),
            sistema_manejo: 'CORRAL',
            total_cabezas: '7',
            peso_total: '1729',
            responsable: 'Encargado de manga',
            observaciones: 'Hoja 1 de 2 del movimiento.',
          },
          rows: [
            { id: '1', pageKey: 'page-1', caravana: 'CA-H1-01', peso_actual: '243.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', destination_key: 'RECRÍA GENERAL 2026', manejo: 'C', observations: '' },
            { id: '2', pageKey: 'page-1', caravana: 'CA-H1-02', peso_actual: '251.0', sexo: 'H', categoria: 'Ternera', dientes: 'DL', destination_key: 'RECRÍA GENERAL 2026', manejo: 'C', observations: '' },
            { id: '3', pageKey: 'page-1', caravana: 'CA-H1-03', peso_actual: '239.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', destination_key: 'RECRÍA GENERAL 2026', manejo: 'C', observations: '' },
            { id: '4', pageKey: 'page-1', caravana: 'CA-H1-04', peso_actual: '256.0', sexo: 'M', categoria: 'Ternero', dientes: '2D', destination_key: 'RECRÍA GENERAL 2026', manejo: 'C', observations: '' },
          ],
        },
        {
          key: 'page-2',
          fileName: 'planilla_cact01_hoja_2.svg',
          hojaNumero: 2,
          hojaTotal: 2,
          metadata: {
            actividad_origen: 'Cría',
            actividad_destino: 'Recría',
            lote_origen: 'Rodeo Cría General',
            lote_destino: 'Recría General 2026',
            fecha_movimiento: new Date().toISOString().slice(0, 10),
            sistema_manejo: 'CORRAL',
            total_cabezas: '7',
            peso_total: '1729',
            responsable: 'Encargado de manga',
            observaciones: 'Hoja 2 de 2 del movimiento.',
          },
          rows: [
            { id: '5', pageKey: 'page-2', caravana: 'CA-H2-05', peso_actual: '247.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', destination_key: 'RECRÍA GENERAL 2026', manejo: 'C', observations: '' },
            { id: '6', pageKey: 'page-2', caravana: 'CA-H2-06', peso_actual: '245.0', sexo: 'H', categoria: 'Ternera', dientes: 'DL', destination_key: 'RECRÍA GENERAL 2026', manejo: 'C', observations: '' },
            { id: '7', pageKey: 'page-2', caravana: 'CA-H2-07', peso_actual: '248.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', destination_key: 'RECRÍA GENERAL 2026', manejo: 'C', observations: '' },
          ],
        },
      ],
    },
    REPAIR_ERROR: {
      templateCode: 'CACT-01',
      scenario: 'REPAIR_ERROR',
      scenarioLabel: '🔴 Flujo de Reparación (Cact01RepairDialog)',
      scenarioDescription:
        'Caravana duplicada entre hojas, una inexistente, una fuera del lote de origen, una dentición ilegible, un peso en cero, un lote nuevo de Cría sin declarar el manejo, un lote nuevo con dos celdas M contradictorias y un lote escrito que pertenece a otra actividad. La barra de reparación abre la guía de errores por tipo.',
      templateTitle: 'Cambio de Actividad de Hacienda',
      category: 'ACTIVITY',
      context: {
        actividad_origen: 'Cría',
        actividad_destino: 'Cría',
        lote_origen: 'Rodeo Cría 1',
        lote_destino: 'Cría Nueva Sin Manejo',
        fecha_movimiento: new Date().toISOString().slice(0, 10),
        sistema_manejo: '',
        total_cabezas: 5,
        peso_total: 1200,
        responsable: 'Manga',
        hoja_numero: 1,
        hoja_total: 2,
        observaciones: 'Simulación de bloqueo por validación del cambio de actividad.',
      },
      rows: [
        { id: '1', caravana: 'CA-DUPLICADA-01', peso_actual: '240.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: '', observations: 'Aparece también en la hoja 2' },
        { id: '2', caravana: 'CA-DUPLICADA-01', peso_actual: '242.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: '', observations: 'Hoja 2' },
        { id: '3', caravana: 'CA-NO-EXISTE-99', peso_actual: '238.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: '', observations: 'No existe en el sistema' },
        { id: '4', caravana: 'CA-OTRO-LOTE-77', peso_actual: '244.0', sexo: 'H', categoria: 'Ternera', dientes: 'xyz', lote_destino: '', observations: 'No está en el lote de origen y la dentición es ilegible' },
        { id: '5', caravana: 'CA-PESO-CERO-55', peso_actual: '0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: '', observations: 'Peso en cero' },
        { id: '6', caravana: 'CA-MANEJO-C-11', peso_actual: '239.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: 'Cría Corral Contradictorio', manejo: 'C', observations: 'Mismo lote nuevo, M = C' },
        { id: '7', caravana: 'CA-MANEJO-P-12', peso_actual: '241.0', sexo: 'M', categoria: 'Ternero', dientes: 'DL', lote_destino: 'Cría Corral Contradictorio', manejo: 'P', observations: 'Mismo lote nuevo, M = P' },
        { id: '8', caravana: 'CA-OTRA-ACTIVIDAD-13', peso_actual: '243.0', sexo: 'H', categoria: 'Ternera', dientes: 'DL', lote_destino: 'Recría Norte', manejo: 'P', observations: 'Ese lote existe, pero es de Recría y la planilla declara Cría' },
      ],
      mockErrors: {
        headerErrors: [
          { field: 'destinations', code: 'MANAGEMENT_SYSTEM_MISSING', message: "Indicá si el lote nuevo 'Cría Nueva Sin Manejo' se maneja a corral o de forma extensiva." },
          { field: 'destinations', code: 'MANAGEMENT_SYSTEM_CONFLICT', message: "El lote nuevo 'Cría Corral Contradictorio' aparece como corral en una fila y como pastura en otra. Un lote es una cosa o la otra." },
          { field: 'destinations', code: 'DESTINATION_ACTIVITY_MISMATCH', message: "El lote 'Recría Norte' es de Recría, pero la planilla declara destino Cría." },
        ],
        rowErrors: [
          { row_index: 1, caravana: 'CA-DUPLICADA-01', errors: [{ code: 'DUPLICATED_IN_SHEET', message: "La caravana 'CA-DUPLICADA-01' ya figura en la fila 1." }] },
          { row_index: 2, caravana: 'CA-NO-EXISTE-99', errors: [{ code: 'NOT_FOUND', message: "No existe la caravana 'CA-NO-EXISTE-99'." }] },
          { row_index: 3, caravana: 'CA-OTRO-LOTE-77', errors: [
            { code: 'NOT_IN_SOURCE_BATCH', message: "La caravana 'CA-OTRO-LOTE-77' no está en el lote 'Rodeo Cría 1'." },
            { code: 'INVALID_TEETH', message: "No se entiende la dentición 'xyz' de la caravana 'CA-OTRO-LOTE-77'. Se esperaba DL, 2D, 4D, 6D, 8D o Boca Llena." },
          ] },
          { row_index: 4, caravana: 'CA-PESO-CERO-55', errors: [{ code: 'INVALID_WEIGHT', message: "El peso de 'CA-PESO-CERO-55' tiene que ser mayor a cero." }] },
        ],
      },
    },
  },
  'DEST-01': {
    HAPPY_PATH: {
      templateCode: 'DEST-01',
      scenario: 'HAPPY_PATH',
      scenarioLabel: '🟢 Destete Tradicional Válido (10 Terneros)',
      scenarioDescription: 'Desmadre tradicional con lote de destete propuesto, crías, madres y pesajes en balanza.',
      templateTitle: 'Destete y Conformación de Lote de Destete',
      category: 'WEANING',
      context: {
        lote_destete: 'Destete Otoño 2026',
        sistema_manejo: 'PASTURA',
        fecha_destete: new Date().toISOString().slice(0, 10),
        tipo_destete: 'TRADICIONAL',
        lote_origen: 'Rodeo Cría 1',
        responsable: 'Encargado de manga',
        hoja_numero: 1,
        hoja_total: 1,
        observaciones: 'Terneros en buen estado sanitario. Destete al pie de madre.',
      },
      rows: [
        { id: '1', caravana: 'TE-201', caravana_madre: 'VC-101', peso: '172.0', sexo: 'M', observations: 'Macho entero' },
        { id: '2', caravana: 'TE-202', caravana_madre: 'VC-102', peso: '185.5', sexo: 'H', observations: 'Hembra recría' },
        { id: '3', caravana: 'TE-203', caravana_madre: 'VC-103', peso: '168.0', sexo: 'M', observations: '' },
        { id: '4', caravana: 'TE-204', caravana_madre: 'VC-104', peso: '192.0', sexo: 'M', observations: 'Excelente peso' },
        { id: '5', caravana: 'TE-205', caravana_madre: 'VC-105', peso: '160.0', sexo: 'H', observations: '' },
        { id: '6', caravana: 'TE-206', caravana_madre: 'VC-106', peso: '178.0', sexo: 'M', observations: '' },
        { id: '7', caravana: 'TE-207', caravana_madre: 'VC-107', peso: '182.5', sexo: 'H', observations: '' },
        { id: '8', caravana: 'TE-208', caravana_madre: 'VC-108', peso: '175.0', sexo: 'M', observations: '' },
      ],
    },
    WARNINGS: {
      templateCode: 'DEST-01',
      scenario: 'WARNINGS',
      scenarioLabel: '🟡 Advertencias (Pesos Extremos & Faltan Madres)',
      scenarioDescription: 'Simula ternero con peso bajo (90 kg) y caravana repetida.',
      templateTitle: 'Destete y Conformación de Lote de Destete',
      category: 'WEANING',
      context: {
        lote_destete: 'Destete Precoz',
        sistema_manejo: 'PASTURA',
        fecha_destete: new Date().toISOString().slice(0, 10),
        tipo_destete: 'PRECOZ',
        lote_origen: 'Rodeo 2',
        responsable: 'Manga',
        hoja_numero: 1,
        hoja_total: 1,
        observaciones: 'Lote con terneros livianos.',
      },
      rows: [
        { id: '1', caravana: 'TE-201', caravana_madre: 'VC-101', peso: '170.0', sexo: 'M', observations: '' },
        { id: '2', caravana: 'TE-201', caravana_madre: 'VC-102', peso: '175.0', sexo: 'H', observations: 'Caravana duplicada' },
        { id: '3', caravana: 'TE-203', caravana_madre: '', peso: '90.0', sexo: 'M', observations: 'Peso bajo para la fecha' },
      ],
    },
    MULTI_PAGE: {
      templateCode: 'DEST-01',
      scenario: 'MULTI_PAGE',
      scenarioLabel: '📄 Flujo Multi-Hoja (Hoja 1 y Hoja 2 de Manga)',
      scenarioDescription: 'Simula 2 hojas escaneadas para probar la barra de navegación de páginas y previsualizaciones independientes.',
      templateTitle: 'Destete y Conformación de Lote de Destete',
      category: 'WEANING',
      context: {
        lote_destete: 'Destete Lote General Multi-Hoja',
        sistema_manejo: 'PASTURA',
        fecha_destete: new Date().toISOString().slice(0, 10),
        tipo_destete: 'TRADICIONAL',
        lote_origen: 'Rodeo Cría General',
        responsable: 'Encargado de manga',
        hoja_numero: 1,
        hoja_total: 2,
        observaciones: 'Lote grande escaneado en dos hojas consecutivas.',
      },
      rows: [
        { id: '1', caravana: 'TE-H1-01', caravana_madre: 'VC-01', peso: '175.0', sexo: 'M', observations: 'Hoja 1' },
        { id: '2', caravana: 'TE-H1-02', caravana_madre: 'VC-02', peso: '180.0', sexo: 'H', observations: 'Hoja 1' },
        { id: '3', caravana: 'TE-H1-03', caravana_madre: 'VC-03', peso: '168.0', sexo: 'M', observations: 'Hoja 1' },
        { id: '4', caravana: 'TE-H1-04', caravana_madre: 'VC-04', peso: '188.0', sexo: 'H', observations: 'Hoja 1' },
      ],
      pages: [
        {
          key: 'page-1',
          fileName: 'planilla_dest01_hoja_1.svg',
          hojaNumero: 1,
          hojaTotal: 2,
          metadata: {
            lote_destete: 'Destete Lote General Multi-Hoja',
            fecha_destete: new Date().toISOString().slice(0, 10),
            tipo_destete: 'TRADICIONAL',
            lote_origen: 'Rodeo Cría General',
            responsable: 'Encargado de manga',
            observaciones: 'Hoja 1 de 2 de destete.',
          },
          rows: [
            { id: '1', pageKey: 'page-1', caravana: 'TE-H1-01', caravana_madre: 'VC-01', peso: '175.0', observations: '' },
            { id: '2', pageKey: 'page-1', caravana: 'TE-H1-02', caravana_madre: 'VC-02', peso: '180.0', observations: '' },
            { id: '3', pageKey: 'page-1', caravana: 'TE-H1-03', caravana_madre: 'VC-03', peso: '168.0', observations: '' },
            { id: '4', pageKey: 'page-1', caravana: 'TE-H1-04', caravana_madre: 'VC-04', peso: '188.0', observations: '' },
          ],
        },
        {
          key: 'page-2',
          fileName: 'planilla_dest01_hoja_2.svg',
          hojaNumero: 2,
          hojaTotal: 2,
          metadata: {
            lote_destete: 'Destete Lote General Multi-Hoja',
            fecha_destete: new Date().toISOString().slice(0, 10),
            tipo_destete: 'TRADICIONAL',
            lote_origen: 'Rodeo Cría General',
            responsable: 'Encargado de manga',
            observaciones: 'Hoja 2 de 2 de destete.',
          },
          rows: [
            { id: '5', pageKey: 'page-2', caravana: 'TE-H2-05', caravana_madre: 'VC-05', peso: '172.0', observations: '' },
            { id: '6', pageKey: 'page-2', caravana: 'TE-H2-06', caravana_madre: 'VC-06', peso: '190.0', observations: '' },
            { id: '7', pageKey: 'page-2', caravana: 'TE-H2-07', caravana_madre: 'VC-07', peso: '165.0', observations: '' },
          ],
        },
      ],
    },
    PER_ANIMAL: {
      templateCode: 'DEST-01',
      scenario: 'PER_ANIMAL',
      scenarioLabel: '🔀 Lote de Destete por Cría (columna Lote destino y M)',
      scenarioDescription:
        'Planilla en blanco con destino por animal: machos a un lote nuevo a pastura y hembras a otro a corral, con C/S nueva escrita en la manga. Al confirmar crea su orden registrada.',
      templateTitle: 'Destete y Conformación de Lote de Destete',
      category: 'WEANING',
      context: {
        orden_destete: '',
        lote_destete: '— por animal —',
        sistema_manejo: '',
        fecha_destete: new Date().toISOString().slice(0, 10),
        tipo_destete: 'TRADICIONAL',
        lote_origen: 'Rodeo Cría 1',
        responsable: 'Encargado de manga',
        hoja_numero: 1,
        hoja_total: 1,
        observaciones: '',
      },
      rows: [
        { id: '1', caravana: 'TE-301', caravana_madre: 'VC-301', peso: '182', sexo: 'M', cs_nueva: 'Novillito', lote_destino: 'Destete Machos Otoño', manejo: 'P', observations: '' },
        { id: '2', caravana: 'TE-302', caravana_madre: 'VC-302', peso: '176', sexo: 'H', cs_nueva: 'Vaquillona / Reposición', lote_destino: 'Destete Hembras Otoño', manejo: 'C', observations: '' },
        { id: '3', caravana: 'TE-303', caravana_madre: 'VC-303', peso: '188', sexo: 'M', cs_nueva: '', lote_destino: 'Destete Machos Otoño', manejo: 'P', observations: '' },
        { id: '4', caravana: 'TE-304', caravana_madre: 'VC-304', peso: '171', sexo: 'H', cs_nueva: '', lote_destino: 'Destete Hembras Otoño', manejo: 'C', observations: '' },
      ],
    },
    REPAIR_ERROR: {
      templateCode: 'DEST-01',
      scenario: 'REPAIR_ERROR',
      scenarioLabel: '🔴 Flujo de Reparación (Dest01RepairDialog)',
      scenarioDescription: 'Simula un fallo 422 con terneros ya destetados o pesos inválidos para verificar la pantalla de reparación y la guía de errores de su barra.',
      templateTitle: 'Destete y Conformación de Lote de Destete',
      category: 'WEANING',
      context: {
        lote_destete: 'Destete Con Errores',
        sistema_manejo: 'PASTURA',
        fecha_destete: new Date().toISOString().slice(0, 10),
        tipo_destete: 'TRADICIONAL',
        lote_origen: 'Rodeo 1',
        responsable: 'Manga',
        hoja_numero: 1,
        hoja_total: 1,
        observaciones: 'Simulación de bloqueo por validación de desmadre.',
      },
      rows: [
        { id: '1', caravana: 'TERNERO-YA-DESTETADO-01', caravana_madre: 'VC-01', peso: '180.0', sexo: 'M', observations: '' },
        { id: '2', caravana: 'TERNERO-INVALIDO-02', caravana_madre: 'VC-02', peso: 'abc', sexo: 'H', observations: 'Peso inválido' },
      ],
      mockErrors: {
        rowErrors: [
          { row_index: 0, caravana: 'TERNERO-YA-DESTETADO-01', errors: [{ code: 'already_weaned', message: 'La cría ya fue desmadrada previamente' }] },
          { row_index: 1, caravana: 'TERNERO-INVALIDO-02', errors: [{ code: 'invalid_weight', message: 'El peso ingresado no es numérico' }] },
        ],
      },
    },
  },

  'REP-01': {
    HAPPY_PATH: {
      templateCode: 'REP-01',
      scenario: 'HAPPY_PATH',
      scenarioLabel: '🟢 Diagnóstico Gestacional Típico (12 Vientres)',
      scenarioDescription: 'Vientres con preñez confirmada (Cabeza, Cuerpo, Cola) y vientres vacíos para separación.',
      templateTitle: 'Planilla de Tacto y Ecografía',
      category: 'REPRODUCTIVE',
      context: {
        lote: 'Rodeo Vacas de Cría 1',
        fecha: new Date().toISOString().slice(0, 10),
        metodo: 'Tacto Rectal y Ecografía',
        observaciones: 'Porcentaje de preñez estimado: 83.3%. Sanidad reproductiva adecuada.',
      },
      rows: [
        { id: 1, caravana: 'VC-001', category: 'Vaca de Cría', diagnosis: 'PREGNANT', gestational_stage: 'CABEZA', observations: 'Preñada ~90 días' },
        { id: 2, caravana: 'VC-002', category: 'Vaca de Cría', diagnosis: 'PREGNANT', gestational_stage: 'CABEZA', observations: 'Preñada cabeza' },
        { id: 3, caravana: 'VC-003', category: 'Vaca de Cría', diagnosis: 'PREGNANT', gestational_stage: 'CUERPO', observations: 'Preñada ~60 días' },
        { id: 4, caravana: 'VC-004', category: 'Vaca de Cría', diagnosis: 'EMPTY', gestational_stage: '-', observations: 'Vacía descarte potencial' },
        { id: 5, caravana: 'VC-005', category: 'Vaquillona', diagnosis: 'PREGNANT', gestational_stage: 'CABEZA', observations: 'Excelente conformación' },
        { id: 6, caravana: 'VC-006', category: 'Vaquillona', diagnosis: 'PREGNANT', gestational_stage: 'COLA', observations: 'Preñada tardía ~35 días' },
        { id: 7, caravana: 'VC-007', category: 'Vaca CUT', diagnosis: 'PREGNANT', gestational_stage: 'CUERPO', observations: 'Último ternero' },
        { id: 8, caravana: 'VC-008', category: 'Vaca de Cría', diagnosis: 'EMPTY', gestational_stage: '-', observations: 'Vacía' },
        { id: 9, caravana: 'VC-009', category: 'Vaca de Cría', diagnosis: 'PREGNANT', gestational_stage: 'CABEZA', observations: 'Preñada cabeza' },
        { id: 10, caravana: 'VC-010', category: 'Vaquillona', diagnosis: 'PREGNANT', gestational_stage: 'CUERPO', observations: 'Preñada cuerpo' },
      ],
    },
    WARNINGS: {
      templateCode: 'REP-01',
      scenario: 'WARNINGS',
      scenarioLabel: '🟡 Alta Tasa de Vacías (Alerta Sanitaria)',
      scenarioDescription: 'Simula más del 50% de vacías en el lote para verificar flujos de desvío a potrero de descarte.',
      templateTitle: 'Planilla de Tacto y Ecografía',
      category: 'REPRODUCTIVE',
      context: {
        lote: 'Rodeo Vacas Cut',
        fecha: new Date().toISOString().slice(0, 10),
        observaciones: 'Alerta: Bajo índice de preñez. Posible problema nutricional o andrológico.',
      },
      rows: [
        { id: 1, caravana: 'VC-101', category: 'Vaca de Cría', diagnosis: 'EMPTY', gestational_stage: '-', observations: 'Vacía' },
        { id: 2, caravana: 'VC-102', category: 'Vaca de Cría', diagnosis: 'EMPTY', gestational_stage: '-', observations: 'Vacía' },
        { id: 3, caravana: 'VC-103', category: 'Vaca de Cría', diagnosis: 'EMPTY', gestational_stage: '-', observations: 'Vacía' },
        { id: 4, caravana: 'VC-104', category: 'Vaca de Cría', diagnosis: 'PREGNANT', gestational_stage: 'COLA', observations: 'Preñada tardía' },
      ],
    },
    REPAIR_ERROR: {} as any,
    MULTI_PAGE: {} as any,
  },

  // Simulated readings of a hand-filled ING-02 (no AI): see ing02SheetCasePresets.
  'ING-02': ING02_PRESETS,

  // Built from the ING-03 test sheets, so the scenario buttons and the sheet list show the same data.
  'ING-03': {
    HAPPY_PATH: { ...ING03_SHEET_CASES[2], scenario: 'HAPPY_PATH' },
    WARNINGS: { ...ING03_SHEET_CASES[0], scenario: 'WARNINGS' },
    REPAIR_ERROR: { ...ING03_SHEET_CASES[1], scenario: 'REPAIR_ERROR' },
  },

  // Built from the PAR-01 test sheets, so the scenario buttons and the sheet list show the same data.
  'PAR-01': {
    HAPPY_PATH: { ...PAR01_SHEET_CASES[1], scenario: 'HAPPY_PATH' },
    WARNINGS: { ...PAR01_SHEET_CASES[8], scenario: 'WARNINGS' },
    MULTI_PAGE: PAR01_WHOLE_ORDER,
    REPAIR_ERROR: { ...PAR01_SHEET_CASES[7], scenario: 'REPAIR_ERROR' },
  },

  'MON-01': {
    HAPPY_PATH: {
      templateCode: 'MON-01',
      scenario: 'HAPPY_PATH',
      scenarioLabel: '🟢 Entore Colectivo a Campo (8 Vientres)',
      scenarioDescription: 'Vientres con condición corporal óptima y toro asignado.',
      templateTitle: 'Servicio de Monta y Entore a Campo',
      category: 'REPRODUCTIVE',
      context: {
        lote: 'Lote Entore Primavera 2026',
        service_type: 'Colectivo',
        planned_start_date: new Date().toISOString().slice(0, 10),
        observaciones: 'Relación toro/vaca: 3.5%. Toros con andrológico apto.',
      },
      rows: [
        { id: 1, caravana: 'VQ-301', category: 'Vaquillona', body_condition: 3.5, sire_caravan: 'TR-001', service_date: new Date().toISOString().slice(0, 10), observations: 'Monta observada 08:00 hs' },
        { id: 2, caravana: 'VQ-302', category: 'Vaquillona', body_condition: 3.5, sire_caravan: 'TR-001', service_date: new Date().toISOString().slice(0, 10), observations: '' },
        { id: 3, caravana: 'VQ-303', category: 'Vaca', body_condition: 3.0, sire_caravan: 'TR-002', service_date: new Date().toISOString().slice(0, 10), observations: '' },
      ],
    },
    WARNINGS: {
      templateCode: 'MON-01',
      scenario: 'WARNINGS',
      scenarioLabel: '🟡 Condición Corporal Baja en Entore (CC < 2.5)',
      scenarioDescription: 'Alerta zootécnica: vientres con CC deficiente que compromete la tasa de ovulación.',
      templateTitle: 'Servicio de Monta y Entore a Campo',
      category: 'REPRODUCTIVE',
      context: {
        lote: 'Lote Entore Alerta CC',
        service_type: 'Individual',
        planned_start_date: new Date().toISOString().slice(0, 10),
        observaciones: 'Revisar suplementación mineral en potrero.',
      },
      rows: [
        { id: 1, caravana: 'VQ-401', category: 'Vaquillona', body_condition: 2.0, sire_caravan: 'TR-001', service_date: new Date().toISOString().slice(0, 10), observations: 'CC baja para entore' },
      ],
    },
    REPAIR_ERROR: {} as any,
    MULTI_PAGE: {} as any,
  },

  'OP-01': {
    HAPPY_PATH: {
      templateCode: 'OP-01',
      scenario: 'HAPPY_PATH',
      scenarioLabel: '🟢 Control de Pesaje Mensual en Recría (8 Animales)',
      scenarioDescription: 'Pesajes de rutina con buena ganancia diaria de peso (0.75 a 0.95 kg/día).',
      templateTitle: 'Control Mensual de Lotes',
      category: 'WEIGHT',
      context: {
        batch_name: 'Recría Lote 3',
        entry_date: new Date().toISOString().slice(0, 10),
        observaciones: 'Pesada de control de rutina en báscula central. Pastura consociada.',
      },
      rows: [
        { id: 1, caravana: 'NV-501', category: 'Novillito', weight: 315.0, body_condition: '3.5', observations: '+25 kg vs mes anterior' },
        { id: 2, caravana: 'NV-502', category: 'Novillito', weight: 328.0, body_condition: '3.5', observations: '+27 kg' },
        { id: 3, caravana: 'NV-503', category: 'Novillito', weight: 305.0, body_condition: '3.0', observations: '+22 kg' },
        { id: 4, caravana: 'NV-504', category: 'Novillito', weight: 340.0, body_condition: '4.0', observations: 'Excelente ganancia' },
      ],
    },
    WARNINGS: {
      templateCode: 'OP-01',
      scenario: 'WARNINGS',
      scenarioLabel: '🟡 Ganancia de Peso Nula o Pérdida',
      scenarioDescription: 'Animales sin ganancia mensual para revisión clínica o desparasitación.',
      templateTitle: 'Control Mensual de Lotes',
      category: 'WEIGHT',
      context: {
        batch_name: 'Recría Lote 3',
        entry_date: new Date().toISOString().slice(0, 10),
        observaciones: 'Atención: Animales con merma de peso.',
      },
      rows: [
        { id: 1, caravana: 'NV-601', category: 'Novillito', weight: 290.0, body_condition: '2.5', observations: 'Pérdida de 5 kg vs mes anterior' },
      ],
    },
    REPAIR_ERROR: {} as any,
    MULTI_PAGE: {} as any,
  },

  'OP-02': {
    HAPPY_PATH: {
      templateCode: 'OP-02',
      scenario: 'HAPPY_PATH',
      scenarioLabel: '🟢 Transferencia a Invernada (Recría -> Feedlot)',
      scenarioDescription: 'Movimiento de tropa terminada de recría hacia corral de engorde.',
      templateTitle: 'Transferencia a Invernada',
      category: 'ACTIVITY',
      context: {
        source_batch: 'Recría Campo Abierto 1',
        target_batch: 'Corral Feedlot Terminación',
        entry_date: new Date().toISOString().slice(0, 10),
        observaciones: 'Pasan a ración de terminación.',
      },
      rows: [
        { id: 1, caravana: 'NV-701', category: 'Novillo', source_batch: 'Recría 1', target_batch: 'Feedlot', observations: 'Listo para encierre' },
        { id: 2, caravana: 'NV-702', category: 'Novillo', source_batch: 'Recría 1', target_batch: 'Feedlot', observations: '' },
      ],
    },
    WARNINGS: {
      templateCode: 'OP-02',
      scenario: 'WARNINGS',
      scenarioLabel: '🟡 Lote Origen y Destino Idénticos',
      scenarioDescription: 'Advertencia de movimiento circular o innecesario.',
      templateTitle: 'Transferencia a Invernada',
      category: 'ACTIVITY',
      context: {
        source_batch: 'Recría 1',
        target_batch: 'Recría 1',
        entry_date: new Date().toISOString().slice(0, 10),
        observaciones: 'Lote de destino coincide con el de origen.',
      },
      rows: [
        { id: 1, caravana: 'NV-801', category: 'Novillo', source_batch: 'Recría 1', target_batch: 'Recría 1', observations: 'Sin cambio' },
      ],
    },
    REPAIR_ERROR: {} as any,
    MULTI_PAGE: {} as any,
  },
};

/**
 * The SHEET_CASES scenario: one preset per test sheet, for the templates that have a set of them.
 */
export const SIMULATION_SHEET_CASES: Record<string, SimulationPreset[]> = {
  'CACT-01': CACT01_SHEET_CASES,
  'DEST-01': DEST01_SHEET_CASES,
  'PAR-01': PAR01_SHEET_CASES,
  'ING-02': ING02_SHEET_CASES,
  'ING-03': ING03_SHEET_CASES,
};

export function getSimulationSheetCases(templateCode: string): SimulationPreset[] {
  return SIMULATION_SHEET_CASES[templateCode] ?? [];
}

/**
 * Returns a simulation preset for the given template code and scenario, with graceful fallbacks.
 */
export function getSimulationPreset(templateCode: string, scenario: SimulationScenario = 'HAPPY_PATH'): SimulationPreset {
  const codePresets = SIMULATION_PRESETS[templateCode] || SIMULATION_PRESETS['ING-01'];
  const requested = codePresets[scenario];

  if (requested && requested.templateCode) {
    return requested;
  }

  // Every template defines its happy path; it is the floor of this catalogue.
  return codePresets['HAPPY_PATH'] as SimulationPreset;
}
